name: Atividade4_GitHub_Actions

on:
  push:
      branches:
        -main

  schedule:   
    - cron: '30 08 * *' # every day 08:30 UTC

jobs:
  Build:

    runs-on: ubutun-latest

    stepes:
      -name: 'Ckeckout Github Action'
        uses: actions/checkout@v4

        -name: Set up NET core
          uses: actions/setup-dotnet@v1
          white:
            dotnet-version '8.0.X'
            
            -name: Build and publish with dotnet
              working-directory: src/Tailwind.Traders.web
              run: |
                dotnet build --configuration Realese
      