name: Super Linter workflow

on:
  schedule:   
    - cron: '30 6 * * 5' # every Friday 6:30 UTC

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: github/super-linter@v3
      env:
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKE }}