name: Módulo4_GitHub_actions

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
      - '*'
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore **/*.csproj
      - name: Build
        run: dotnet build **/*.csproj --no-restore